invitation_list = ['Jesus Christ','Teófilo Hayashi','Pr. Marcelo Pinheiro','Pr. Jeferson Silva', 'Pr. Luiz Roberto', 'Mateus Andriu', 'Romeu Alves',
                   'Ingrid Cristina','Vitória Oliveira']

print(invitation_list[0].title() + " May you come to my dinner? Your Presence is so precious for us")
print(invitation_list[1].title() + " Can you come to our dinner?")
print(invitation_list[2].title() + " Dear pastor, your Presence is requested to a dinner ")
print(invitation_list[3].title() + " You are invitated to our dinner :) ")
print(invitation_list[4].title() + " Big pastor, may you come to our dinner?")
print(invitation_list[5].title() + " Our Leader, maybe you can go to our dinner...")
print(invitation_list[5].title() + " Can't go :/ \n")
invitation_list[5] = 'Isadora Duarte'

print(invitation_list[0].title() + " May you come to my dinner? Your Presence is so precious for us")
print(invitation_list[1].title() + " Can you come to our dinner?")
print(invitation_list[2].title() + " Dear pastor, your Presence is requested to a dinner ")
print(invitation_list[3].title() + " You are invitated to our dinner :) ")
print(invitation_list[4].title() + " Big pastor, may you come to our dinner?")
print("Hi "+ invitation_list[5].title() +"! can you be with us for a dinner?")
print("Hello! I've found a bigger table, so we can sit with more people\n")

invitation_list.insert(0,'Our Father')
invitation_list.insert(4,"Pra. Luana Simi")
invitation_list.append('Nay')

print("\nNew Invitation")
print(invitation_list[0].title() + " Father, may you come to our dinner? Your Presence is so precious for us")
print(invitation_list[1].title() + " Lord, may you can be with us in our dinner?")
print(invitation_list[2].title() + " Bro, Can you come to our dinner?")
print(invitation_list[3].title() + " Dear pastor, your Presence is requested to a dinner ")
print(invitation_list[4].title() + " You are invitated to our dinner :) ")
print(invitation_list[5].title() + " Hi miss, can you be with us for a dinner?")
print(invitation_list[6].title() + " Big pastor, may you come to our dinner?")
print("Hi "+ invitation_list[7].title() +"! can you be with us for a dinner?")
print("Hi my dear disciple " + invitation_list[8] +", can you be with us in this thinner")
print("Hello " + invitation_list[9] + " can you come for a dinner?")
print("Hi!!! " + invitation_list[10] + "  may you be with us on a dinner?")
print("Hello " + invitation_list[11].title() + " You are so special, you can't miss this dinner, please, stay with us")
print(str(len(invitation_list))+ " Invitations")
print("\nFor Now you can invite only 2 people\n")

print(invitation_list)
guest = invitation_list.pop(1)
print("Dear " + guest + " I'm so sorry but i can't invite you for this dinner...")
guest = invitation_list.pop(2)
print("Dear " + guest + " I'm so sorry but i can't invite you for this dinner...")
guest = invitation_list.pop(3)
print("Dear " + guest + " I'm so sorry but i can't invite you for this dinner...")
guest = invitation_list.pop(4)
print("Dear " + guest + " I'm so sorry but i can't invite you for this dinner...")
guest = invitation_list.pop(5)
print("Dear " + guest + " I'm so sorry but i can't invite you for this dinner...")
guest = invitation_list.pop(6)
print("Dear " + guest + " I'm so sorry but i can't invite you for this dinner...")
guest = invitation_list.pop()
print("Dear " + guest + " I'm so sorry but i can't invite you for this dinner...")
guest = invitation_list.pop()
print("Dear " + guest + " I'm so sorry but i can't invite you for this dinner...")
guest = invitation_list.pop()
print("Dear " + guest+ " I'm so sorry but i can't invite you for this dinner...")
guest = invitation_list.pop()
print("Dear " + guest + " I'm so sorry but i can't invite you for this dinner...")


print(invitation_list)
del invitation_list[1]
del invitation_list[0]
print(invitation_list)